{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spacelift-worker.fullname" . }}
  labels:
    {{- include "spacelift-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.credentials.token | quote }}
  privateKey: {{ .Values.credentials.privateKey | quote }}
{{- end }}
