{{- if .Values.drain.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spacelift.drainServiceAccountName" . }}
  labels:
    {{- include "spacelift.drainLabels" . | nindent 4 }}
  {{- with .Values.drain.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.drain.serviceAccount.automount }}
{{- end }}
