apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mqttService.name }}
  {{- with .Values.mqttService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "spacelift.serverLabels" . | nindent 4 }}
spec:
  type: {{ .Values.mqttService.type }}
  {{- with .Values.mqttService.additionalSpec }}
    {{- toYaml . | nindent 2}}
  {{- end }}
  ports:
    - port: {{ .Values.mqttService.port }}
      targetPort: mqtt
      protocol: TCP
      name: server
  selector:
    {{- include "spacelift.serverSelectorLabels" . | nindent 4 }}
