{{- if .Values.scheduler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spacelift.schedulerServiceAccountName" . }}
  labels:
    {{- include "spacelift.schedulerLabels" . | nindent 4 }}
  {{- with .Values.scheduler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.scheduler.serviceAccount.automount }}
{{- end }}
