apiVersion: v1
kind: Service
metadata:
  name: {{ include "spacelift.fullname" . }}-server
  labels:
    {{- include "spacelift.serverLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      protocol: TCP
      name: server
  selector:
    {{- include "spacelift.serverSelectorLabels" . | nindent 4 }}
