{{- if and .Values.vcsGateway.enabled .Values.vcsGateway.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vcs-gateway
  labels:
    {{- include "spacelift.vcsGatewayLabels" . | nindent 4 }}
spec:
  parentRefs:
    - name: vcs-gateway
  hostnames:
    - {{ required "vcsGateway.domain is required when vcsGateway is enabled" .Values.vcsGateway.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "spacelift.fullname" $ }}-vcs-gateway
          port: {{ .Values.vcsGateway.externalPort }}
{{- end }}
