{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcs-agent.fullname" . }}
  labels:
    {{- include "vcs-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.credentials.token | quote }}
  endpoint: {{ .Values.credentials.endpoint | quote }}
  vendor: {{ .Values.credentials.vendor | quote }}
{{- end }}
