{{- if and .Values.credentials.create (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcs-agent.fullname" . }}
  labels:
    {{- include "vcs-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.tokenSecretKey }}: {{ .Values.credentials.token | quote }}
  {{ .Values.credentials.endpointSecretKey }}: {{ .Values.credentials.endpoint | quote }}
  {{ .Values.credentials.vendorSecretKey }}: {{ .Values.credentials.vendor | quote }}
{{- end }}
