apiVersion: v1
kind: Service
metadata:
  name: {{ include "spacelift-flows.fullname" . }}-server
  labels:
    {{- include "spacelift-flows.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: public
  selector:
    {{- include "spacelift-flows.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server