apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spacelift-flows.fullname" . }}-worker
  labels:
    {{- include "spacelift-flows.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "spacelift-flows.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "spacelift-flows.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag  }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy  }}
          command: [ "/usr/bin/spacelift-flows" ]
          args:
            - "worker"
          env:
            - name: CONFIG_FILE
              value: "/etc/flows/config.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/flows
              readOnly: true
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{.Values.secretName}}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}