apiVersion: v1
kind: Secret
metadata:
  name: spacelift-flows-secret
  namespace: flows
stringData:
  config.yaml: |
    appDomain: "flows.yourdomain.com"
    
    openTelemetry:
      collectorEndpoint: "opentelemetry-collector.otel-collector.svc.cluster.local:4317"
      environment: "production"
    
    selfHosted:
      organizationName: "yourorganization"
      adminEmail: "admin@yourdomain.com"
      licenseToken: {{ env "LICENSE_TOKEN" }}

    databaseUrl: {{ env "DATABASE_URL" }}
    # example postgresql://{user}:{password}@flows-postgres-rw.flows.svc.cluster.local:5432/flows
    
    defaultAgentPool:
      id: "{your-uuid}"
      token: "{your-token}"
    
    server:
      listeners:
        http:
          port: 8080
      public:
        listeners:
          - listenerId: http
      internal:
        listeners:
          - listenerId: http
    
    email:
      smtp:
        host: smtp.gmail.com
        port: 587
        username: "{ your smtp username }"
        password: {{ env "SMTP_PASSWORD" }}
        fromAddress: "{your smtp from address}"
        fromName: "Flows"
        encryption: "starttls"
      dev:
        enabled: false

    objectStorage:
      s3:
        bucket: flows
        accessKeyId: {your-access-key}
        secretAccessKey: {your-secret-key}
        region: us-east-1
        endpoint: {your-endpoint}
        insecure: true/false
