name: Production chart publish

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}-chart-publish-prod

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/job_chart-publish.yaml
    with:
      chart_version_strategy: tag

      r2_bucket: ${{ vars.R2_BUCKET }}
      r2_endpoint: ${{ vars.R2_ENDPOINT_URL }}

      cloudflare_zone_id: ${{ vars.EU_DOWNLOADS_CLOUDFLARE_ZONE_ID }}
      cloudflare_purge_prefix: downloads.spacelift.io/helm/

      smoke_pull_repo_url: https://downloads.spacelift.io/helm
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
      cf_distribution_id: ${{ secrets.DISTRIBUTION }}
      r2_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
      r2_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      cloudflare_purge_token: ${{ secrets.EU_CLOUDFLARE_CACHE_PURGE_TOKEN }}
