name: Preprod chart publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-chart-publish-preprod

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/job_chart-publish.yaml
    with:
      chart_version_strategy: timestamp
      chart_version_prefix: 0.0.1-preprod

      r2_bucket: ${{ vars.PREPROD_R2_BUCKET }}
      r2_endpoint: ${{ vars.PREPROD_R2_ENDPOINT_URL }}

      cloudflare_zone_id: ${{ vars.PREPROD_DOWNLOADS_CLOUDFLARE_ZONE_ID }}
      cloudflare_purge_prefix: downloads.spacelift.dev/helm/

      smoke_pull_repo_url: https://downloads.spacelift.dev/helm
      smoke_pull_devel: true
    secrets:
      aws_region: ${{ secrets.PREPROD_AWS_REGION }}
      aws_role_to_assume: ${{ secrets.PREPROD_AWS_ROLE_TO_ASSUME }}
      aws_s3_bucket: ${{ secrets.PREPROD_AWS_S3_BUCKET }}
      cf_distribution_id: ${{ secrets.PREPROD_DISTRIBUTION }}
      r2_access_key_id: ${{ secrets.PREPROD_R2_ACCESS_KEY_ID }}
      r2_secret_access_key: ${{ secrets.PREPROD_R2_SECRET_ACCESS_KEY }}
      cloudflare_purge_token: ${{ secrets.PREPROD_CLOUDFLARE_CACHE_PURGE_TOKEN }}
