name: Check self-hosted chart tests

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "spacelift-self-hosted/**"
      - ".github/workflows/test-self-hosted-chart.yml"

jobs:
  test:
    name: Run spacelift-self-hosted Helm tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Run Helm unit tests
        working-directory: spacelift-self-hosted
        run: make test
