{{- define "rules" -}}
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - pods
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - watch
- apiGroups:
    - workers.spacelift.io
  resources:
    - workerpools
    - workers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - workers.spacelift.io
  resources:
    - workerpools/finalizers
    - workers/finalizers
  verbs:
    - update
- apiGroups:
    - workers.spacelift.io
  resources:
    - workerpools/status
    - workers/status
  verbs:
    - get
    - patch
    - update
{{ end -}}
{{ if default .Values.controllerManager.namespaces | empty }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-manager-role
  labels:
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
rules:
{{ include "rules" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-manager-rolebinding
  labels:
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "spacelift-workerpool-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: {{ include "spacelift-workerpool-controller.serviceAccountName" . }}
  namespace: '{{ .Release.Namespace }}'
{{ else }}
{{ range $index, $namespace := .Values.controllerManager.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: '{{ $namespace }}'
  name: {{ include "spacelift-workerpool-controller.fullname" $ }}-manager-role
  labels:
  {{- include "spacelift-workerpool-controller.labels" $ | nindent 4 }}
rules:
{{ include "rules" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" $ }}-manager-rolebinding
  namespace: '{{ $namespace }}'
  labels:
  {{- include "spacelift-workerpool-controller.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "spacelift-workerpool-controller.fullname" $ }}-manager-role'
subjects:
  - kind: ServiceAccount
    name: {{ include "spacelift-workerpool-controller.serviceAccountName" $ }}
    namespace: '{{ $.Release.Namespace }}'
{{ end }}
{{ end }}
