apiVersion: v1
kind: Service
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: spacelift-workerpool-controller
    app.kubernetes.io/part-of: spacelift-workerpool-controller
    control-plane: controller-manager
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "spacelift-workerpool-controller.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}
