{{ if and .Values.metricsService.enabled .Values.metricsService.secure }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-metrics-auth-role
  labels:
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-metrics-auth-rolebinding
  labels:
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "spacelift-workerpool-controller.fullname" . }}-metrics-auth-role'
subjects:
  - kind: ServiceAccount
    name: {{ include "spacelift-workerpool-controller.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-metrics-reader
  labels:
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{ end }}
