{{ if .Values.metricsService.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-metrics-reader
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: spacelift-workerpool-controller
    app.kubernetes.io/part-of: spacelift-workerpool-controller
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{ end }}
