{{ if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "spacelift-workerpool-controller.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}
{{ end }}
