apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spacelift-workerpool-controller.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spacelift-workerpool-controller
    app.kubernetes.io/part-of: spacelift-workerpool-controller
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}