{{- if .Values.controllerManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spacelift-workerpool-controller.serviceAccountName" . }}
  labels:
  {{- include "spacelift-workerpool-controller.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
{{- end }}
